# Generated by Django 6.0.1 on 2026-01-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('visit', 'Visit'), ('online_meeting', 'Online Meeting'), ('call', 'Call'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('missed', 'Missed')], default='planned', max_length=20)),
                ('outcome_notes', models.TextField(blank=True)),
                ('next_action_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_spoken_to', models.CharField(blank=True, max_length=100)),
                ('person_role', models.CharField(blank=True, max_length=100)),
                ('frameworks_discussed', models.JSONField(blank=True, default=list)),
                ('confirmed_client_types', models.CharField(blank=True, max_length=20)),
                ('infrastructure_discussed', models.CharField(blank=True, max_length=20)),
                ('deployment_pain_points', models.TextField(blank=True)),
                ('time_spent_on_deployments', models.CharField(blank=True, max_length=50)),
                ('cost_spent_on_deployments', models.CharField(blank=True, max_length=50)),
                ('effort_and_team_involved', models.TextField(blank=True)),
                ('partnership_interest', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_discussed', 'Not discussed')], default='not_discussed', max_length=20)),
                ('interest_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('cloud_spending_range', models.CharField(blank=True, max_length=50)),
                ('demo_video_shared', models.BooleanField(default=False)),
                ('kuberns_explained_clearly', models.BooleanField(default=False)),
                ('roadmap_clear', models.BooleanField(default=False)),
                ('deployment_roadmap', models.TextField(blank=True)),
                ('next_steps_agreed', models.TextField(blank=True)),
                ('meeting_permitted', models.BooleanField(default=True)),
                ('meeting_declined', models.BooleanField(default=False)),
                ('decline_reason', models.TextField(blank=True)),
                ('meeting_rescheduled', models.BooleanField(default=False)),
                ('reschedule_reason', models.TextField(blank=True)),
                ('suggested_followup_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visits',
            },
        ),
    ]
