# Generated by Django 6.0.1 on 2026-01-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('decision_maker', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('sales_nurture', 'Sales Nurture'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('frameworks_used', models.JSONField(blank=True, default=list, help_text='List of frameworks')),
                ('infrastructure', models.CharField(blank=True, choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('on_prem', 'On-prem'), ('mixed', 'Mixed')], max_length=20)),
                ('client_type', models.CharField(blank=True, choices=[('indian', 'Indian'), ('foreign', 'Foreign'), ('both', 'Both')], max_length=20)),
                ('cloud_spending', models.CharField(blank=True, help_text='Monthly estimate', max_length=50)),
                ('decision_maker', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('intent', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('research_notes', models.TextField(blank=True)),
                ('closing_strategy', models.TextField(blank=True)),
                ('partnership_interest', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_discussed', 'Not discussed')], default='not_discussed', max_length=20)),
                ('won_reason', models.TextField(blank=True)),
                ('lost_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-updated_at'],
            },
        ),
    ]
